name: Update Docker Compose Password with Secrets

on:
  push:
    branches:
      - dev

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace password in docker-compose.yml
      run: |
        sed -i "s/POSTGRES_PASSWORD: .*/POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}/" docker-compose.yml
        cat docker-compose.yml

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add docker-compose.yml
        git commit -m "Update Docker Compose password with GitHub secret"
        git push origin dev
