name: Update Docker Compose Password with Secrets

on:
  push:
    branches:
      - dev
      - staging

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display the current POSTGRES_PASSWORD value
      run: |
        grep POSTGRES_PASSWORD docker-compose.yml

    - name: Replace password in docker-compose.yml
      run: |
        sed -i "s/POSTGRES_PASSWORD: .*/POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}/" docker-compose.yml
        echo "Updated docker-compose.yml:"
        cat docker-compose.yml

    - name: Replace password in database.json
      run: |
        jq --arg password "${{ secrets.PG_PASSWORD }}" \
           '.development.password = $password |
            .test.password = $password |
            .production.password = $password' \
            packages/backend/src/config/database.json > tmp.json && mv tmp.json packages/backend/src/config/database.json
        echo "Updated database.json:"
        cat packages/backend/src/config/database.json

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add docker-compose.yml packages/backend/src/config/database.json
        git commit -m "Update Docker Compose and database.json password with GitHub secret" || echo "No changes to commit"
        git push origin dev

    - name: Push changes to repository
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/maryluis/pet-monorepo.git HEAD:dev
